# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55c6f95feb8ac32ad2214370dce70fc9de26d18855e14fa5125044b16722756e09531cc0cac914dd57dedda59017a66a77241040908e1a7f09031da60336972e

test:
  secret_key_base: 4b5b9e8d389b70bd3d60b80db9994d5493b77dbf347fd6564edba97377ec7483e49ef67eda53121a0b5b7ef30d21f2fe6415450daffd57449041d58329dd7d63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
